examples/clock/package.json
examples/clock/src/App.tsx
examples/clock/src/index.tsx
examples/clock/src/model.ts
examples/clock/tsconfig.json
examples/random/src/model.ts
examples/timers/package.json
examples/timers/src/App.tsx
examples/timers/src/actions.ts
examples/timers/src/index.tsx
examples/timers/src/store.ts
examples/timers/tsconfig.json
packages/core/src/events.ts
packages/core/src/model.ts
packages/core/src/store.ts
packages/core/src/streams.ts
packages/core/src/types.ts
packages/core/tests/store.test.ts
packages/stream-plugin/package.json
packages/stream-plugin/src/index.ts
packages/stream-plugin/tests/index.test.ts
packages/stream-plugin/tsconfig.json
tsconfig.json

Changes the streams to use a plugin. This is somewhat limited, but much more robust.
Note: streams are added immediately, not upon action completion. Need to look at this again.

Streams plugin

---

packages/eslint-plugin/src/rules/require-dispatched-action-is-called.ts
packages/eslint-plugin/src/types/rules.ts
packages/eslint-plugin/tests/rulesTs/require-dispatched-action-is-called.test.ts

Fixing types for eslint plugin. Enumerated the possible visitors with 
```
[key: string]:
| ((node: TSESTree.ImportDeclaration) => void)
| ((node: TSESTree.CallExpression) => void)
```
for lack of a better option (to the best of my understanding of typescript) right now and so that I don't just have 'any' as type.

fix types for eslint-plugin

---

packages/stream-plugin/package.json

I thought it already was. Not sure if we should be publishing this when it doesn't work with the transpiler.
https://github.com/prodo-ai/prodo/issues/66

Make stream plugin private

---

packages/stream-plugin/src/index.ts

The `Streams` type is now complete, and the transform to `Partial<Streams>` is done in `prepareViewCtx`. This makes the user type easier to work with in generics (no need to `Required` it everywhere), and also makes it clear that there is (currently) no way to have an always-defined stream value.

Merge stream changes from KDB branch

---

examples/chat-app/.babelrc
examples/chat-app/package.json
examples/clock/.babelrc
examples/clock/package.json
examples/kanban-with-db/.babelrc
examples/kanban-with-db/package.json
examples/kanban/.babelrc
examples/kanban/package.json
examples/local-map/.babelrc
examples/local-map/package.json
examples/random/.babelrc
examples/random/package.json
examples/routing/.babelrc
examples/routing/package.json
examples/timers/.babelrc
examples/timers/package.json
examples/todo-app/.babelrc
examples/todo-app/package.json
examples/transpilation/.babelrc
examples/transpilation/package.json
examples/update-testing/.babelrc
examples/update-testing/package.json

- Add core-js to all examples `.babelrc` and `package.json`
- Add readme to kanban app example
Address this
```
WARNING: We noticed you're using the `useBuiltIns` option without declaring a
core-js version. Currently, we assume version 2.x when no version is passed.
Since this default version will likely change in future versions of Babel, we
recommend explicitly setting the core-js version you are using via the `corejs`
option.
You should also be sure that the version you pass to the `corejs` option matches
the version specified in your `package.json`'s `dependencies` section. If it
doesn't, you need to run one of the following commands:
npm install --save core-js@2    npm install --save core-js@3
yarn add core-js@2              yarn add core-js@3
```

Fix core js warning

---

examples/kanban/src/store.tsx
packages/devtools-core/src/App/DevTools/ActionLogPanel/index.tsx
packages/devtools-core/src/App/DevTools/RenderLogPanel/index.tsx
packages/devtools-core/src/App/DevTools/components/ClearLogsButton.tsx
packages/devtools-core/tests/actions/index.test.ts
packages/devtools-core/tests/components/DevTools/ActionLogPanel/ActionLogRow.test.tsx
packages/devtools-core/tests/components/DevTools/ActionLogPanel/index.test.tsx
packages/devtools-core/tests/components/DevTools/RenderLogPanel/index.test.tsx
packages/devtools-core/tests/components/DevTools/StatePanel.test.tsx
packages/devtools-core/tests/components/DevTools/components/JsonTree.test.tsx
packages/devtools-core/tests/components/DevTools/index.test.tsx
packages/devtools-core/tests/components/index.test.tsx
packages/devtools-core/tests/fixtures.tsx
packages/devtools-core/tests/utils.tsx

Currently clears both logs, since they are both based off of the same data. Can separate functionality if people prefer though.

Devtools - Add a button to clear action and render logs

---

packages/create-prodo-app/package.json
packages/create-prodo-app/src/index.ts
packages/create-prodo-app/src/logger.ts
packages/create-prodo-app/tsconfig.json
tsconfig.json
yarn.lock

Script similar to https://github.com/facebook/create-react-app/blob/master/packages/create-react-app/createReactApp.js
This package needs to `create-prodo-app` on NPM so we can use [yarn create](https://yarnpkg.com/lang/en/docs/cli/create/) and [npx](https://www.npmjs.com/package/npx) easily.
Creating a prodo app
- Checks if app name is valid
- Checks if app directory does not exist
- Downloads either [prodo-template-js](https://github.com/prodo-ai/prodo-template-js/) or [prodo-template](https://github.com/prodo-ai/prodo-template/) depending on if the `--typescript` option was provided
- Remove references to prodo in users `app package.json`

Create Prodo App

---

docs/content/02_basics/devtools.md
docs/content/03_plugins/devtools.md
examples/kanban/package.json
examples/kanban/src/model.tsx
examples/todo-app/package.json
examples/todo-app/src/model.ts
packages/devtools-core/.babelrc
packages/devtools-core/README.md
packages/devtools-plugin/package.json

Would close https://github.com/prodo-ai/prodo/issues/108#event-2662330277 (and start on https://github.com/prodo-ai/prodo/issues/109#event-2662493838  by moving devtools-core from dev to real dependencies)
Edit: the corejs fix may help with the react-editable-json-tree problem too.

Rename devtools-plugin to devtools

---

packages/devtools-core/package.json

I think this should fix https://github.com/prodo-ai/prodo/issues/109.
The errors were of the form:
```
ERROR in ./node_modules/react-editable-json-tree/dist/components/JsonObject.js
Module not found: Error: Can't resolve 'babel-runtime/core-js/object/get-own-property-names' in '/Users/andrejakogovsek/Projects/ak-app/node_modules/react-editable-json-tree/dist/components'
```
Adding this to my prodo app dev dependencies made the errors go away.

Fix devtools dependencies

---

docs/yarn.lock

Why do the docs have their own yarn.lock file?

Commit docs/yarn.lock

---

docs/src/styles/highlight.css

More padding for inline code

---

packages/devtools-core/src/App/UserAppContainer/index.tsx

Chrome doesn't really trigger "load" events on the iFrame, so we have to trigger it manually.
(also noticed one of the options was missing the handler, but it did seem to be working okay before...)
Would close https://github.com/prodo-ai/prodo/issues/124

Make sure load is called in Chrome

---

docs/content/01_introduction/benefits.md
docs/content/01_introduction/installation.md

After adding create-prodo-app, we have removed all information on how to just install prodo with npm or yarn. This PR adds an installation page in the introduction. Address feedback in https://github.com/prodo-ai/prodo/issues/132.

Add installation page to the docs

---

packages/eslint-plugin/src/configs/base.json
packages/eslint-plugin/src/configs/recommended.ts
packages/eslint-plugin/src/index.ts

Fixing mistake from #138:
- no default export
- typo in path for base.json, but the contents of that file aren't actually necessary.

fix typo, simplify and no default export

---

packages/eslint-plugin/src/utils/findDefinition.ts
packages/eslint-plugin/tests/rulesTs/no-state-access.test.ts

Simple fix for bug. I saw the following error when linting a file that included builtin variables (`Date`, `console` etc). Fixed by checking that the definition exists before accessing node in the `findDefinition` function. 
```TypeError: Cannot read property 'node' of undefined
Occurred while linting /prodo/examples/chess-app/src/App.tsx:6
at Object.exports.findDefinition (/prodo/packages/eslint-plugin/lib/utils/findDefinition.js:10:60)
at CallExpression:not(CallExpression > CallExpression.callee) (/prodo/packages/eslint-plugin/lib/rules/require-dispatched-action-is-called.js:40:58)
at listeners.(anonymous function).forEach.listener (/prodo/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
at Array.forEach (<anonymous>)
at Object.emit …
```

check def exists before accessing node

---

packages/babel-plugin/package.json
packages/core/package.json
packages/create-prodo-app/package.json
packages/devtools-core/package.json
packages/devtools-plugin/package.json
packages/eslint-plugin/package.json
packages/local-plugin/package.json
packages/logger-plugin/package.json
packages/route-plugin/package.json

I know that when I publish the eslint-plugin lerna will fail because it is a scoped package and we do not have private packages enabled for the `@prodo` org. This PR follows this https://github.com/lerna/lerna/pull/1139, which will hopefully publish publically initially. 🤞

add publishConfig to all public packages

---

docs/content/01_introduction/examples.md
docs/content/05_tutorials/github-prs.md

Do we want an embeded codesandbox on the homepage of the docs?

Embed codesandbox in examples and tutorial

---

docs/content/01_introduction/getting-started.md

The app created from create-prodo-app is different then the one created when the getting-started guide was written. This PR updates the getting started guide to use routes and code highlighting.

Update getting started to new prodo-template

---

examples/benchmark/.babelrc
examples/benchmark/README.md
examples/benchmark/package.json
examples/benchmark/src/AppProdo.tsx
examples/benchmark/src/AppRedux.tsx
examples/benchmark/src/Controls.tsx
examples/benchmark/src/index.html
examples/benchmark/src/index.scss
examples/benchmark/src/index.tsx
examples/benchmark/src/lib.ts
examples/benchmark/src/model.ts
examples/benchmark/tsconfig.json
examples/benchmark/webpack.config.js
packages/core/src/watch.ts
tsconfig.json
yarn.lock

Previously, react did some work immediately after setState was called.
If a single action triggered state changes in many elements, this caused
updates to be quite slow - up to 1000x vs Redux.
unstable_batchedUpdates is used by Redux to avoid this:
https://react-redux.js.org/api/batch#references.

Use unstable_batchedUpdates to group setState

---

docs/content/05_tutorials/github-prs.md

I noticed that the section that menitons styling in the tutorial comes a bit late in the tutorial. This PR moves that section above any visual part of the tutorial.

Mention styling in github pr list tutorial earlier

---

docs/src/components/DocsLayout.tsx

I'm pretty sure these used to work, but now they don't. This PR forces the current pathname in front of the hash.

Fix toc hash links

---

packages/gatsby-plugin/README.md
packages/gatsby-plugin/package.json
packages/gatsby-plugin/src/gatsby-node.js
yarn.lock

Oops, I merged https://github.com/prodo-ai/prodo/pull/160 early
Rename `@prodo/gatsby-plugin` to `gatsby-plugin-prodo` to follow gatsby plugin naming conventions https://www.gatsbyjs.org/docs/naming-a-plugin/.

Rename to gatsby plugin

---

docs/content/03_plugins/local.md
docs/content/03_plugins/routing.md
examples/local-map/package.json
examples/local-map/src/index.tsx
examples/local-map/src/model.ts
examples/local-map/tsconfig.json
packages/local-plugin/src/index.ts
packages/local-plugin/tests/index.test.ts

Previously the local plugin would only capture updates made to the top level of `universe.local`. So this would work (update universe and browser local storage)
```ts
local.a = "foo"
```
but this would not
```ts
local.a.b = "foo"
```
This PR makes the second example work. It also supports deleting of local storage items.
Instead of using a proxy to trap `set` calls to `universe.local`, I instead use the plugin `onCompleteEvent` hook to update local storage (if not in fixtures mode) with the new state of the universe and remove any values that were deleted. Some notable changes:
- `config.initLocal` values are store in local storage
- local storage is only read from once in init. This behaves more like local storage middleware for redux

Local plugin nested values

---

docs/content/01_introduction/getting-started.md

Mention some action rules earlier on in the docs in case people don't get to the separate Actions page.

Emphasize actions can't return anything earlier on

---

docs/content/03_plugins/local.md
packages/local-plugin/src/index.ts
packages/local-plugin/src/utils.ts
packages/local-plugin/tests/index.test.ts

1. Remove the `localFixture` and instead have make the local storage injectable. 
2. Falls back to an in memory storage if local storage is not enabled.
3. Sets local storage immediately from `initLocal` on init.
Closes #194.

Save local storage init

---

packages/core/src/store.ts
packages/core/tests/store.test.ts

Without this, dispatching a second action while awaiting the result of a first action would cause the first dispatch call to never resolve, since we were using a singleton on the store. This updates it so that neither dispatch call will resolve until the both are done.
Not sure if this is the best approach - thoughts?

Fix multiple dispatches
