prodo-dev/prodo

packages/babel-plugin/src/components-and-actions.ts
packages/babel-plugin/src/inject-universe.ts
packages/babel-plugin/tests/actions.test.ts
packages/babel-plugin/tests/components.test.tsx
packages/core/src/connect.tsx
packages/core/src/events.ts
packages/core/src/store.ts
packages/core/src/types.ts
packages/firestore-plugin/src/index.ts
packages/local-plugin/src/index.ts
packages/stream-plugin/src/index.ts
tsconfig.common.json

tsconfig `"strict": true` and make ts happy

Enable ts strict mode and fix errors

---

examples/clock/README.md
examples/clock/index.html
examples/clock/package.json
examples/clock/tsconfig.json
examples/todo-app/.babelrc
examples/todo-app/README.md
examples/todo-app/index.html
examples/todo-app/package.json
examples/todo-app/src/App.tsx
examples/todo-app/src/actions.ts
examples/todo-app/src/model.ts
examples/todo-app/tests/actions.test.ts
examples/todo-app/tests/components.test.tsx
examples/todo-app/tsconfig.json
examples/transpilation/package.json
packages/local-plugin/package.json
yarn.lock

Test out making the todo app and clock app work on code sandbox out of the box
- move `index.html` files to root of example
- convert todo app to use transpiler
- add `"jsx": "react"` to all `tsconfig`s

Codesandbox examples

---

packages/core/src/connect.tsx
packages/core/src/model.ts
packages/core/src/types.ts

Better type for `Model.with`

---

package.json
yarn.lock

Add firebase tools package

---

packages/local-plugin/src/index.ts

When saving stuff to local-storage, prefix everything that's handled by prodo with `prodo:`, and ignore everything else. This is because some services (such as webpack-dev-server) will also write to local storage.

All local stuff goes behind prodo:

---

README.md
examples/clock/README.md
examples/todo-app/README.md
packages/babel-plugin/README.md
packages/core/README.md
packages/effect-plugin/README.md
packages/eslint-plugin/README.md
packages/firestore-plugin/README.md
packages/local-plugin/README.md
packages/logger-plugin/README.md
packages/route-plugin/README.md
packages/stream-plugin/README.md

- update main readme
- add readme to published npm packages
- update readme to some examples

Readme improvements

---

docs/content/03_plugins/firestore.md
docs/content/03_plugins/streams.md
docs/content/04_advanced/creating-plugins.md
docs/src/components/Banner.tsx
docs/src/components/DocsLayout.tsx
docs/src/components/GithubIcon.tsx
docs/src/components/Header.tsx
docs/src/pages/404.tsx
docs/src/templates/Docs.tsx

- Fix github icon
- better 404 page
- Add banner on experimental and wip pages

Docs improvements

---

packages/core/src/plugins.ts
packages/core/src/store.ts

```tsx
plugin.setProvider(provider: React.ComponentType);
```

Ability for plugin to set provider

---

packages/core/src/plugins.ts
packages/core/src/store.ts
packages/route-plugin/src/actions.ts
packages/route-plugin/src/plugin.ts
packages/route-plugin/src/types.ts
packages/route-plugin/tests/index.test.ts

Also means we don't need to remember to update the universe manually any more.
Before:
After:

Make sure the back button works

---

docs/gatsby-config.js
docs/package.json
docs/src/components/Search.tsx
docs/src/components/Sidebar.tsx
docs/yarn.lock
yarn.lock

Add search to docs that will filter the sidebar based on your query. Right now it only searches based on the doc title and slug, but we can easily extend this if we want.

Docs Search

---

examples/kanban/package.json
examples/kanban/src/components/List/ListHeader.tsx
examples/kanban/src/model.tsx
examples/kanban/src/store.tsx
examples/kanban/tsconfig.json
packages/devtools-core/src/App/UserAppContainer/ErrorBoundary.tsx
packages/devtools-core/src/App/UserAppContainer/index.tsx
packages/devtools-core/src/App/index.tsx
packages/devtools-core/src/index.tsx
packages/devtools-core/src/styles/theme.ts

Fixes https://github.com/prodo-ai/prodo/issues/87
The issue was that the value of "cards" wasn't being updated properly inside the onSelection handler in the Wrapper component, even though it looked like it was updating correctly inside ListHeader. May be an issue with react-aria-menubutton 🤷‍♀ 
Also took this opportunity to add an error boundary into the devtools (pretty much copied from before). There's also a quick hack to make devtools work with react-modal in the kanban example.

Kanban "delete list" bug fix

---

examples/todo-app/tests/components.test.tsx

`waitForDomChange` is more robust and what we recommend in the docs

Replace setTimeout awaits with waitForDomChange

---

packages/devtools-core/package.json
packages/devtools-core/src/App/DevTools/index.tsx
packages/devtools-core/src/App/UserAppContainer/index.tsx
yarn.lock

I'm having issues with getting react-scroll-to-bottom to work properly, so for now just take it out and use regular scrolling (this will fix https://github.com/prodo-ai/prodo/issues/125 for now)

Devtools scroll patch

---

packages/eslint-plugin/src/configs/base.json
packages/eslint-plugin/src/configs/recommended.ts
packages/eslint-plugin/src/index.ts

Eslint config

---

docs/src/components/Caret.tsx
docs/src/components/Search.tsx
docs/src/components/SearchIcon.tsx
docs/src/components/Sidebar.tsx
docs/src/styles/highlight.css
docs/src/styles/index.ts

- Update sidebar search
- Update sidebar headings
- Update code theme
Before
After

Update docs styling

---

docs/content/05_tutorials/github-prs.md

Fixes some of the code in the tutorial. This addresses some issues a user was having.
- Use `IPullRequest` everywhere
- Add `rel="noopener noreferrer"` to pull request a tag

Fix tutorial code

---

packages/logger-plugin/src/index.ts

Closes https://github.com/prodo-ai/prodo/issues/61

Show plugin name in logger meta output

---

examples/routing/package.json
examples/routing/src/index.tsx
examples/routing/src/model.ts
examples/routing/src/pages/Home.tsx
examples/routing/src/pages/Profile.tsx
examples/routing/tsconfig.json
packages/devtools-core/src/App/UserAppContainer/index.tsx
packages/devtools-core/src/App/index.tsx
packages/devtools-core/src/index.tsx
yarn.lock

Based off https://github.com/prodo-ai/prodo/pull/170
Should close https://github.com/prodo-ai/prodo/issues/159
Watches the app route to make sure that we update styled components when they change.
Hope you don't mind me adding devtools & styled components to the routing example for quick testing.

Fix devtools styled components

---

package.json
packages/gatsby-plugin/package.json
yarn.lock

- don't fail if clean command is missing
- commit updated yarn lock (not sure why this was out of date)

Exclude missing clean

---

README.md

Maybe should also add something to the docs?

Add Slackin link to readme

---

docs/content/01_introduction/getting-started.md
docs/content/01_introduction/installation.md

Add some instructions on what to do in case you get the "Incorrect integrity when fetching from the cache" error.

Docs - Cache Error Info

---

packages/local-plugin/src/index.ts

see https://github.com/prodo-dev/prodo/commit/3162d26977c55984b9aae9d05f104dabe524994a#comments

use hasOwnProperty everywhere

---

packages/core/src/store.ts
packages/core/src/types.ts

Track next action name

---

packages/core/src/store.ts

Isn't a problem with the bundled TS version (TS 3.5.10, but does cause an issue in my editor (VSCode 1.43.1, TS 3.8.3).

Fix TS type
